### ISSUE TITLE
sd-webui is a fork of https://github.com/AUTOMATIC1111/stable-diffusion-webui

### ISSUE THREAD

**Issue by ReinerBforartists** [awesome-stable-diffusion/awesome-stable-diffusion#15]
As the title says, sd-webui is a fork of https://github.com/AUTOMATIC1111/stable-diffusion-webui

The Automatic version has things that the fork does not have. Like loopback and outpainting. The sd-webui fork might also have a legal problem. The original repo has no license yet. And so the fork is not on safe ground. No license means the whole code is currently under copyright. Without the right to modify and redistribute it.

**Comment by georgzoeller** [comment]
ok will review

**Comment by gadicc** [comment]
Is that correct?

From [sd-webui](https://github.com/sd-webui/stable-diffusion-webui#stable-diffusion-web-ui) README:

> Original script with Gradio UI was written by a kind anonymous user. This is a modification.

From [AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui#credits) README:

> Initial Gradio script - posted on 4chan by an Anonymous user. Thank you Anonymous user.

I don't know any background, just recall reading those in the respective READMEs.  So from what I understand, both were forked from the same place.  If that code doesn't have a license, not sure... but sounds like it was posted anonymously on a public forum.  Not a lawyer :sweat_smile:

**Comment by georgzoeller** [comment]
replaced since the upstream is better maintained.
