### ISSUE TITLE
Deforum notebook

### ISSUE THREAD

**Issue by pharmapsychotic** [awesome-stable-diffusion/awesome-stable-diffusion#20]
May I suggest the addition of Deforum? It's a Colab notebook for Stable Diffusion with 2D, 3D, Video Input, and Interpolation animations. Includes inpainting, prompt batching, and other nice features too. Under active development with latest version 0.4 from this past weekend.
https://github.com/deforum/stable-diffusion

**Comment by georgzoeller** [comment]
done
