### ISSUE TITLE
Multiple updates

### ISSUE THREAD

**Issue by underlines** [awesome-stable-diffusion/awesome-stable-diffusion#28]
Sorry I am on mobile and can't do a PR.

One question:

Wouldn't it make sense to have sd-webui and AUTOMATIC1111's forks both in the same section?

And then some updates that I didn't find in your list yet:

- [12.5GB Dreambooth colab notebook](https://www.reddit.com/r/StableDiffusion/comments/xphaiw/dreambooth_stable_diffusion_training_in_just_125/)
- [16GB Dreambooth colab notebook](https://www.reddit.com/r/StableDiffusion/comments/xplck5/dreambooth_stable_diffusion_working_on_google/) 
- [amrrs/stable-diffusion-prompt-inpainting](https://github.com/amrrs/stable-diffusion-prompt-inpainting) Prompt Inpainting using masks via natural language
- [Maks-s/sd-akashic](https://github.com/Maks-s/sd-akashic) Collection of studies, art styles, prompts and other useful tools
- [HelixNGC7293/DeforumStableDiffusionLocal](https://github.com/HelixNGC7293/DeforumStableDiffusionLocal) Local version of Deforum Stable Diffusion, supports txt settings file input and animation features!
- [stable-diffusion-webui-docker](https://github.com/AbdBarho/stable-diffusion-webui-docker) Easy Docker setup for Stable Diffusion with AUTOMATIC1111, hlky and lstein's GUI all in one
- [nateraw/stable-diffusion-videos](https://github.com/nateraw/stable-diffusion-videos) Create 🔥 videos with Stable Diffusion by exploring the latent space and morphing between text prompts
- [divamgupta/diffusionbee-stable-diffusion-ui](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui) Diffusion Bee is the easiest way to run Stable Diffusion locally on your M1 Mac. Comes with a one-click installer. No dependencies or technical knowledge needed.
- [NickLucche/stable-diffusion-nvidia-docker](https://github.com/NickLucche/stable-diffusion-nvidia-docker) GPU-ready Dockerfile to run stable-diffusion with a simple web interface. Includes multi-GPUs support.
- [ahrm/UnstableFusion](https://github.com/ahrm/UnstableFusion) A Stable Diffusion desktop frontend with inpainting, img2img and more!
- [Fictiverse/StableDiffusion-Windows-GUI](https://github.com/Fictiverse/StableDiffusion-Windows-GUI) A windows interface for stable diffusion
- [ThereforeGames/txt2mask](https://github.com/ThereforeGames/txt2mask) Addon for AUTOMATIC1111 GUI to inpaint using masks via natural language, supports multiple objects by using keyword1|keyword2|keyword3

**Comment by georgzoeller** [comment]
reviewing

**Comment by georgzoeller** [comment]
- consolidated UIs
- Added Docker

**Comment by georgzoeller** [comment]
Added txtmask for Automatic1111
